---
- hosts: localhost
  vars:
      es_api_reindex:
          query:
              range:
                  "@timestamp":
                      gte: "{{date}}.00:00:00||+{{hour}}h/h"
                      lte: "{{date}}.00:00:00||+{{hour}}h/h"
                      format: "yyyy.MM.dd.HH:mm:ss"
  roles:
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 0}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 1}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 2}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 3}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 4}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 5}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 6}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 7}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 8}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 9}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 10}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 11}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 12}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 13}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 14}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 15}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 16}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 17}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 18}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 19}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 20}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 21}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 22}
      - {role: CyVerse-Ansible.es_api_reindex,
         hour: 23}
